WORK_AREA_CREATE = """
    CREATE TABLE IF NOT EXISTS work_area_{0}_{1} (
        geocode VARCHAR(15) NOT NULL,
        total_jobs INTEGER,
        age_29_under INTEGER,
        age_30_54 INTEGER,
        age_55_over INTEGER,
        earnings_1250_under INTEGER,
        earnings_1251_3333 INTEGER,
        earnings_3333_over INTEGER,
        cns01 INTEGER,
        cns02 INTEGER,
        cns03 INTEGER,
        cns04 INTEGER,
        cns05 INTEGER,
        cns06 INTEGER,
        cns07 INTEGER,
        cns08 INTEGER,
        cns09 INTEGER,
        cns10 INTEGER,
        cns11 INTEGER,
        cns12 INTEGER,
        cns13 INTEGER,
        cns14 INTEGER,
        cns15 INTEGER,
        cns16 INTEGER,
        cns17 INTEGER,
        cns18 INTEGER,
        cns19 INTEGER,
        cns20 INTEGER,
        cr01 INTEGER,
        cr02 INTEGER,
        cr03 INTEGER,
        cr04 INTEGER,
        cr05 INTEGER,
        cr07 INTEGER,
        ct01 INTEGER,
        ct02 INTEGER,
        cd01 INTEGER,
        cd02 INTEGER,
        cd03 INTEGER,
        cd04 INTEGER,
        cs01 INTEGER,
        cs02 INTEGER,
        cfa01 INTEGER,
        cfa02 INTEGER,
        cfa03 INTEGER,
        cfa04 INTEGER,
        cfa05 INTEGER,
        cfs01 INTEGER,
        cfs02 INTEGER,
        cfs03 INTEGER,
        cfs04 INTEGER,
        cfs05 INTEGER,
        createdate DATE,
        segment VARCHAR,
        PRIMARY KEY (geocode, segment)
    )
"""

RES_AREA_CREATE = """
    CREATE TABLE IF NOT EXISTS res_area_{0}_{1} (
        geocode VARCHAR(15) NOT NULL,
        total_jobs INTEGER,
        age_29_under INTEGER,
        age_30_54 INTEGER,
        age_55_over INTEGER,
        earnings_1250_under INTEGER,
        earnings_1251_3333 INTEGER,
        earnings_3333_over INTEGER,
        cns01 INTEGER,
        cns02 INTEGER,
        cns03 INTEGER,
        cns04 INTEGER,
        cns05 INTEGER,
        cns06 INTEGER,
        cns07 INTEGER,
        cns08 INTEGER,
        cns09 INTEGER,
        cns10 INTEGER,
        cns11 INTEGER,
        cns12 INTEGER,
        cns13 INTEGER,
        cns14 INTEGER,
        cns15 INTEGER,
        cns16 INTEGER,
        cns17 INTEGER,
        cns18 INTEGER,
        cns19 INTEGER,
        cns20 INTEGER,
        cr01 INTEGER,
        cr02 INTEGER,
        cr03 INTEGER,
        cr04 INTEGER,
        cr05 INTEGER,
        cr07 INTEGER,
        ct01 INTEGER,
        ct02 INTEGER,
        cd01 INTEGER,
        cd02 INTEGER,
        cd03 INTEGER,
        cd04 INTEGER,
        cs01 INTEGER,
        cs02 INTEGER,
        createdate DATE,
        segment VARCHAR,
        PRIMARY KEY (geocode, segment)
    )
"""

OD_CREATE = """
    CREATE TABLE IF NOT EXISTS origin_dest_{0}_{1} (
        h_geocode VARCHAR(15) NOT NULL,
        w_geocode VARCHAR(15) NOT NULL,
        PRIMARY KEY (h_geocode, w_geocode)
    )
"""

